# Generated by Django 2.2 on 2020-02-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspub',
            options={'ordering': ['-pub_time']},
        ),
    ]
