# Generated by Django 2.2 on 2020-03-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newscomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='author',
            new_name='commentator',
        ),
    ]
