# Generated by Django 2.2 on 2020-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200301_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.URLField()),
                ('priority', models.IntegerField()),
                ('carousel_url', models.URLField()),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
