# Generated by Django 2.2 on 2020-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewscategory',
            name='dispaly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='dispaly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newspub',
            name='dispaly',
            field=models.BooleanField(default=True),
        ),
    ]
