# Generated by Django 2.2 on 2020-07-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200725_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addnewscategory',
            old_name='dispaly',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='newscomment',
            old_name='dispaly',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='newspub',
            old_name='dispaly',
            new_name='display',
        ),
    ]
