# Generated by Django 2.2 on 2020-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.URLField(default=None),
        ),
    ]
