# Generated by Django 2.2 on 2020-03-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_teacher_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id']},
        ),
    ]
