# Generated by Django 2.2 on 2020-05-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_teacher_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='parent',
        ),
    ]
