# Generated by Django 2.2 on 2020-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_teacher_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dispaly',
            field=models.BooleanField(default=True),
        ),
    ]
