# Generated by Django 2.2 on 2020-07-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_teacher_dispaly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dispaly',
            new_name='display',
        ),
    ]
